sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product dmtn-142
env:
  global:
    -
      # LTD_AWS_ID
      secure: ncCf6lhbDvZKmfEZlr2wyAxwnorSFW+PDkgIZ2wzgv8QwlFuS2ar06oEfrWHK3hcU2AxwH+eb4VODcjHzKq1wQdRMD8gFodE4qliA1bcXopM9oNinMV4oIqOiy4PQMbzDYxVRp2DFQAhKyN3IsYTGTtKIvL0w7eHbXdl5BW0f9gjkXYH1fYPEKl8Q4lOCoKwpVG1M/l9iLrgRl9m/27hnbBcG2Wr/uwYiS1KzChl9KNw9Q6si6WdFAk9Z36edrjzpqKa9d2+2J/hvVRRPx4JeMvDcwfNWVA5g+3Av9B2Fx0uRk+/ynsT2rEDxJbiUb+K1yE7npmWiwErZrW+3oDEWlirHxbHfMYHlPNC5jfTESi8b1xD90njz+NR0PEdBtA3uSYgRrr+tEbuXuvzpCKGanx4RWhHhMPoYd4/O3XIinoE7UvIWLTJPildVuPo3nZtDM4OnxtilLhF5JLrIqSl2p1//rpacmZkDSq7y1mV5PA7Tu8hrTFzQDg0JJWPfkKwx54JZ1UVNIAesAmArC3O+9IeY9yfo1Wt16ZwEth8qM/YTevCXqrDlGvjJM72YBcJFm3thP9Dl8apwQe8bUYFkp01MUcHow0gRdbn2Z/dsV1b6/3qpzogmBjmhVcwNtYscYbLFZGzVuFWL4udTMDqdge9SPUu4q4Qi2uXaeLKePs=
    -
      # LTD_AWS_SECRET
      secure: nqWS53xBZjEz8sfn8fxsOonhYXnh4QtzijowV1g6w6wb60Wbxl9CuJFLPX6BHvxci8x0gGwPM6HxsfyYkfdlwhRVgWZ90kcsPwKruUAgrttaYaG/I69Feb3lxNqQBpFevyUAC6CbphfEVhjTxs8NKqYpaIw0/k3AOmiokyGeEQgXHlKgdXIfQALFph4pNtn8yXJ6QYYDf6Rocgx0CjGpD8/Z5sVJcmmb6LtuRy1I3mGfgYqUMVP+D5YNHgITXbJF67I969mzdofQbPv80pB5AyxgrrQePJqa3hVSLJpw+NLf0FpkI68xnSey6UeCbXcuwsyx/skPlnGMA+waz4n+cBFU5ihCt+Ulnl0ocSE/t0YufHhTq0ncBHR/xmF/Qaey6ENV5gmINQqNHhjKADliMXp7K9WUnkEaQVlX0yzofmkOtB7HCi7I0fFlDRmNo4wqqQNwSOq27nspsILIap1LHWLUDcOpFaEazBW9uMonF6g5WSMswgXexv5xsXaGUyo2tCkipRhnhEafw8MaxVWTsTkpodPMVf5ZecgE2P67YWbp/mSwC1vlytmDqQf0Zddv6X1jQ3NMcOTGA5sAic55PgyWTGoIBM1NbJXW4uthsw8td9JLm9tmYTg0M0Lb43tKBvrKm0yQEnR3T4WwTJg2jY1+N7b9iaFhhJBzWaiNcn0=
    -
      # LTD_USERNAME
      secure: iH5rfjKgYLxAEIv87+yaQMCqNmXYEgORtMmfNfd9yCIpkDEd6bgbNki4gFIFwan7NhI6+CoQkIEDZkgDOiQRQcpxYHCXV3QnMnJbIuTz3Af1YoewmYmZfovjqJ8c/oiP/hzV3s2MfTuJqkNfgpm73wTLUktD2yDMstmgQXjFhmtwmqtOfL4ieDi/LGMbG6eQO/yBwh+j4sbI7gaHyLqxNCOM6tGfBUwLE1ZtS+EWclkIILU+FVz5JtwGK/aCC3G9Zw7ienXUfpfoCauDJNHef4U7nhlu07RvSjcFkrxXx2QFGAV5oFh/dgk4FPklI7OOaIFXQhWpgR2VUkTjhFfNf1m25/3xGxdI8LmSSuiH1tMM4hEOZEhLtlGuWQy87WnU8L+Iryr+kv/7N8q1hYiUW1RUwj1nSoZffGCEfi/NBWdEg7N4ZHKbzDKmUoQAqkUcVQMkx7GFuv4L5vA4EQC2wfDs6medeOAUt7phD10Gos33Dir5wM62e5+Hz/IHhKW7RmbYYro2A815Rmkbx9Zxy54KLD47CpOC947oh8uzVjB3mZpaCWyJmUtDb694VNcFtboxBd1by/Pv1zuxroqLvugXrwmBAPjZKgulJZVlns7Ry9JpNdbl+e4DPy4pzoJ8i9Fh3+EfPl4U7mRJENAty5DIIfI5WTdgt7mw2PMWZQU=
    -
      # LTD_PASSWORD
      secure: EaTrxJbRQtDtcfHRZrIdxzFVSOO40gc9j+S91kkMh37VY5MuIp5/yLcBW4rIPCulvHun9wLOqwwl7HEVFf6w/dmwCqEXP1LPW6yhT5KkSeXzkv+u6l5FX1hW+a6RLEQAWWxWNF0ytnbaKnRnt4NeKZqIAmpINRbRXq8n6uD93VOoUHCXw2RTj/IZ+2oJVpoWbNH8CAxM0mN6voLzZn/dutdv0bytv66CPihXvgPnKWPh+mFDGF7t7AkKBDpgjnFy4JtcaVdsmBmwe5vNgA56deG35tYP81Qo+DIXdnnq4qQxN7STIs6TCK7fJ4/Nls7qpF8TUGiPf6YEpjuMQaBtBF/UHrMoBa7X2vxYNo7KM7aqxNEvTsWf+x1sPZ4TX3Ndl1f7a29469TVSDDOgpkYKtArjQwCzBWUlH0WQYDdKYCp32LT4HbQrVcMPX57qRb5bqdX4HCWb7VlugiCZHSmkbCVqZyuAyFVNd3qp2he1DGiTmXwLzqGohxZPSLkOvQ8mZm4K6WGO15vVEITjHfk5oZOIj80yJobwJbo0iFnS0BHyqGxPXOTuA4B5ZmVSrXm8FHh19tw3DpGyCW4Vgg3Rftl8h7K+OEZzhs/nrooDaAdrRDsRIpiuYV07TGy+zAO1vtaIX93EB4sMH4l1WsOP7Sb7bja86/R6zu8lFFVqSw=
